export const POSTS = [
  {
    "id": "01_crm_phone_r",
    "sys": "crm",
    "type": "phone",
    "week": 1,
    "day": "السبت",
    "time": "09:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "🔵 بتتابع عملاءك إزاي؟\n\nمع منطق CRM — كل عميل ليه ملف كامل، كل صفقة متتبعة، وكل فرصة في مكانها الصح.\n\n✅ رؤية ٣٦٠ درجة لكل عميل\n✅ تنبيهات المتابعة التلقائية\n✅ سجل كامل لكل تواصل\n\n📲 جرب منطق مجاناً — اللينك في البايو\n\n#منطق #CRM #إدارة_العملاء #برنامج_محاسبة #مصر",
    "en": "🔵 How do you track your clients?\n\nWith MANTIQ CRM — every client has a full profile, every deal is tracked, every opportunity in its place.\n\n✅ 360° view of every client\n✅ Automated follow-up alerts\n✅ Complete communication history\n\n📲 Try MANTIQ free — link in bio\n\n#MANTIQ #CRM #ClientManagement #Egypt #BusinessSoftware",
    "img": "/images/01_crm_phone_r.png"
  },
  {
    "id": "02_crm_laptop_leads",
    "sys": "crm",
    "type": "laptop",
    "week": 1,
    "day": "الاثنين",
    "time": "12:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "📊 خط أنابيب المبيعات بتاعك واضح قد إيه؟\n\nمع منطق — شوف كل عميلك في أي مرحلة، وتعرف الخطوة الجاية على طول.\n\n✅ لوحة متابعة الصفقات بالكامل\n✅ توقع الإيراد قبل نهاية الشهر\n✅ تقارير الفوز والخسارة\n\n#منطق #مبيعات #CRM #مصر",
    "en": "📊 How clear is your sales pipeline?\n\nWith MANTIQ — see every client at every stage and always know the next step.\n\n✅ Full deals tracking board\n✅ Revenue forecast before month-end\n✅ Win/loss reports\n\n#MANTIQ #Sales #CRM #Egypt",
    "img": "/images/02_crm_laptop_leads.png"
  },
  {
    "id": "03_crm_qa1",
    "sys": "crm",
    "type": "qa",
    "week": 1,
    "day": "الأربعاء",
    "time": "18:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "❓ بتضيع صفقات بسبب عدم المتابعة؟\n\nده مش تقصير منك — ده نظام ناقص.\n\nمع منطق CRM:\n✅ تتبع كل عميل من أول تواصل حتى الإغلاق\n✅ تنبيهات تلقائية قبل ما الصفقة تبرد\n✅ لوحة مرئية لكل مراحل المسار\n✅ سجل كامل لكل مكالمة ورسالة وميتنج\n\n💬 قولنا في الكومنتات — اتضيع منك صفقة قبل كده؟\n\n#منطق #CRM #مبيعات #إدارة_أعمال #مصر",
    "en": "❓ Losing deals because of poor follow-up?\n\nThat's not your fault — it's a broken system.\n\nWith MANTIQ CRM:\n✅ Track every client from first contact to close\n✅ Automatic alerts before deals go cold\n✅ Visual board for every pipeline stage\n✅ Full log of every call, message, and meeting\n\n💬 Tell us in the comments — have you ever lost a deal?\n\n#MANTIQ #CRM #Sales #BusinessManagement #Egypt",
    "img": "/images/03_crm_qa1.png"
  },
  {
    "id": "04_crm_tablet_dash",
    "sys": "crm",
    "type": "tablet",
    "week": 1,
    "day": "الجمعة",
    "time": "15:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "🖥️ لوحة القيادة اللي بتحتاجها\n\nكل أرقامك في مكان واحد — العملاء، الصفقات، الإيراد، وأداء الفريق.\n\nمع منطق، قرارات المبيعات بتاعتك مبنية على بيانات حقيقية مش تخمين.\n\n#منطق #CRM #لوحة_قيادة #مصر",
    "en": "🖥️ The dashboard you actually need\n\nAll your numbers in one place — clients, deals, revenue, and team performance.\n\nWith MANTIQ, your sales decisions are built on real data, not guesswork.\n\n#MANTIQ #CRM #Dashboard #Egypt",
    "img": "/images/04_crm_tablet_dash.png"
  },
  {
    "id": "05_crm_phone_l",
    "sys": "crm",
    "type": "phone",
    "week": 2,
    "day": "السبت",
    "time": "09:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "📈 ٦٢٪ معدل الفوز — مش رقم عشوائي\n\nده نتيجة نظام CRM صح.\n\n٤.٢ مليون جنيه قيمة الصفقات النشطة — كلها مرئية ومتتبعة في منطق.\n\n🎯 اعرف مين هيوافق ومين محتاج push\n\n#منطق #CRM #مبيعات #مصر",
    "en": "📈 62% win rate — not a random number\n\nThat's the result of the right CRM system.\n\n4.2M EGP in active deals — all visible and tracked in MANTIQ.\n\n🎯 Know who's ready to close and who needs a push\n\n#MANTIQ #CRM #Sales #Egypt",
    "img": "/images/05_crm_phone_l.png"
  },
  {
    "id": "06_crm_big_phone",
    "sys": "crm",
    "type": "phone",
    "week": 2,
    "day": "الاثنين",
    "time": "12:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "📋 الصفقات المفتوحة — كلها في لمح البصر\n\n٨٤ صفقة نشطة، كل واحدة عارف حالتها وقيمتها واحتمال فوزها.\n\nمع منطق، مش هتنسى صفقة تاني.\n\n✅ ERP Migration — 420K EGP — تفاوض\n✅ Cloud Setup — 340K EGP — عرض سعر\n✅ Analytics — 128K EGP — مؤهل\n\n#منطق #CRM #صفقات #مصر",
    "en": "📋 Open deals — all visible at a glance\n\n84 active deals, each with clear status, value, and win probability.\n\nWith MANTIQ, you'll never forget a deal again.\n\n✅ ERP Migration — 420K EGP — Negotiation\n✅ Cloud Setup — 340K EGP — Proposal\n✅ Analytics — 128K EGP — Qualified\n\n#MANTIQ #CRM #Deals #Egypt",
    "img": "/images/06_crm_big_phone.png"
  },
  {
    "id": "07_crm_laptop_light",
    "sys": "crm",
    "type": "laptop",
    "week": 2,
    "day": "الأربعاء",
    "time": "18:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "💼 إدارة عملاء ذكية وسهلة\n\nمتابعة بصرية • تقييم الصفقات • تقارير الفوز والخسارة\n\nكل ده في منطق CRM — نظام واحد بيحل مشاكل كتير.\n\n#منطق #CRM #إدارة_العملاء #مصر",
    "en": "💼 Smart and easy client management\n\nVisual tracking • Deal scoring • Win/loss reports\n\nAll of this in MANTIQ CRM — one system that solves many problems.\n\n#MANTIQ #CRM #ClientManagement #Egypt",
    "img": "/images/07_crm_laptop_light.png"
  },
  {
    "id": "08_crm_qa2",
    "sys": "crm",
    "type": "qa",
    "week": 2,
    "day": "الجمعة",
    "time": "15:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "❓ فريق المبيعات بتاعك منظم؟\n\nلو الإجابة مش 'أيوه ١٠٠٪' — في مشكلة محتاج تحلها.\n\nمع منطق CRM:\n✅ صلاحيات مخصصة لكل عضو في الفريق\n✅ تقارير أداء كل مندوب تلقائياً\n✅ تسجيل نقاط للعملاء المحتملين\n✅ تصدير PDF و Excel بضغطة واحدة\n\n💬 كومنت بـ 'نعم' لو عايز تجربة مجانية\n\n#منطق #CRM #فريق_المبيعات #مصر",
    "en": "❓ Is your sales team organized?\n\nIf the answer isn't '100% yes' — there's a problem you need to fix.\n\nWith MANTIQ CRM:\n✅ Custom roles for every team member\n✅ Auto performance reports per rep\n✅ Lead scoring\n✅ Export PDF & Excel in one click\n\n💬 Comment 'YES' for a free trial\n\n#MANTIQ #CRM #SalesTeam #Egypt",
    "img": "/images/08_crm_qa2.png"
  },
  {
    "id": "09_crm_feat1",
    "sys": "crm",
    "type": "features",
    "week": 2,
    "day": "الأحد",
    "time": "11:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "🔵 CRM Tracker — نظام إدارة العملاء الأكثر ذكاءً\n\n• لوحة متابعة الصفقات\n• تسجيل نقاط للعملاء\n• توقع الفوز بالذكاء الاصطناعي\n• تقارير PDF تلقائية\n• صلاحيات المستخدمين\n• سجل الأنشطة الكامل\n\nكل ده جزء من منطق — نظام الأعمال المصري الأول.\n\n#منطق #CRM #برنامج_مصري #إدارة_أعمال",
    "en": "🔵 CRM Tracker — The smartest client management system\n\n• Deals tracking board\n• Lead scoring\n• AI win prediction\n• Auto PDF reports\n• User permissions\n• Full activity log\n\nAll part of MANTIQ — Egypt's #1 business system.\n\n#MANTIQ #CRM #EgyptianSoftware #BusinessManagement",
    "img": "/images/09_crm_feat1.png"
  },
  {
    "id": "10_crm_feat2",
    "sys": "crm",
    "type": "features",
    "week": 2,
    "day": "الثلاثاء",
    "time": "19:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "📊 الأرقام بتتكلم\n\n١٬٢٤٠ عميل مُدار\n٨٤ صفقة نشطة\n٦٢٪ معدل الفوز\n٤.٢M جنيه pipeline\n\nكل الأرقام دي من شركة واحدة بتستخدم منطق CRM.\n\nعايز تشوف أرقامك إيه؟ 👇\n\n#منطق #CRM #مصر #نتائج",
    "en": "📊 Numbers don't lie\n\n1,240 clients managed\n84 active deals\n62% win rate\n4.2M EGP pipeline\n\nAll these numbers from one company using MANTIQ CRM.\n\nWant to see your own numbers? 👇\n\n#MANTIQ #CRM #Egypt #Results",
    "img": "/images/10_crm_feat2.png"
  },
  {
    "id": "11_sls_phone_r",
    "sys": "sls",
    "type": "phone",
    "week": 3,
    "day": "السبت",
    "time": "09:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "🟠 حقق حصتك — كل شهر\n\nمنطق للمبيعات — فرص وعروض وطلبات وعمولات في نظام واحد.\n\n✅ تتبع لحظي للإيراد\n✅ عمولات محتسبة تلقائياً\n✅ أهداف المندوبين مرئية\n\n#منطق #مبيعات #Sales #مصر",
    "en": "🟠 Hit your quota — every single month\n\nMANTIQ Sales — opportunities, quotes, orders, and commissions in one system.\n\n✅ Real-time revenue tracking\n✅ Auto-calculated commissions\n✅ Rep targets made visible\n\n#MANTIQ #Sales #Egypt",
    "img": "/images/11_sls_phone_r.png"
  },
  {
    "id": "12_sls_laptop_orange",
    "sys": "sls",
    "type": "laptop",
    "week": 3,
    "day": "الاثنين",
    "time": "12:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "💰 ٢.١ مليون جنيه إيراد — نمو ١٦٪\n\nمش صدفة — ده نتيجة نظام مبيعات صح.\n\nمنطق بيساعدك تتتبع كل طلب وكل فرصة وكل عمولة.\n\n#منطق #مبيعات #إيراد #مصر",
    "en": "💰 2.1M EGP revenue — 16% growth\n\nNot luck — the result of the right sales system.\n\nMANTIQ helps you track every order, every opportunity, every commission.\n\n#MANTIQ #Sales #Revenue #Egypt",
    "img": "/images/12_sls_laptop_orange.png"
  },
  {
    "id": "13_sls_qa1",
    "sys": "sls",
    "type": "qa",
    "week": 3,
    "day": "الأربعاء",
    "time": "18:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "❓ عارف إيه مندوبيك بيعملوا دلوقتي؟\n\nلو مش متأكد — في مشكلة.\n\nمع منطق للمبيعات:\n✅ أداء كل مندوب في لوحة قيادة مخصصة\n✅ نسبة تحقيق الحصة لحظة بلحظة\n✅ عمولات محتسبة تلقائياً بعد كل صفقة\n✅ تنبيهات لما المندوب يتأخر عن الهدف\n\n💬 قولنا — بتتابع فريقك إزاي؟\n\n#منطق #مبيعات #فريق_المبيعات #مصر",
    "en": "❓ Do you know what your sales reps are doing right now?\n\nIf you're not sure — there's a problem.\n\nWith MANTIQ Sales:\n✅ Each rep's performance in a dedicated dashboard\n✅ Quota attainment tracked in real time\n✅ Commissions auto-calculated after every deal\n✅ Alerts when a rep falls behind target\n\n💬 Tell us — how do you track your team?\n\n#MANTIQ #Sales #SalesTeam #Egypt",
    "img": "/images/13_sls_qa1.png"
  },
  {
    "id": "14_sls_tablet",
    "sys": "sls",
    "type": "tablet",
    "week": 3,
    "day": "الجمعة",
    "time": "15:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "🎯 تتبع المندوبين بدقة\n\nأداء كل مندوب في لوحة قيادة مخصصة — مش spreadsheet.\n\nمنطق بيحول بيانات الفريق لقرارات واضحة.\n\n#منطق #مبيعات #فريق #مصر",
    "en": "🎯 Track your reps with precision\n\nEach rep's performance in a dedicated dashboard — not a spreadsheet.\n\nMANTIQ turns team data into clear decisions.\n\n#MANTIQ #Sales #Team #Egypt",
    "img": "/images/14_sls_tablet.png"
  },
  {
    "id": "15_sls_phone_l",
    "sys": "sls",
    "type": "phone",
    "week": 4,
    "day": "السبت",
    "time": "09:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "📦 الطلبات والعروض — كلها منظمة\n\n١٣٨ طلب مُغلق هذا الشهر — كلهم متتبعين في منطق.\n\nمن أول عرض السعر لحد تسليم المنتج — كل خطوة مسجلة.\n\n#منطق #مبيعات #طلبات #مصر",
    "en": "📦 Orders and quotes — fully organized\n\n138 orders closed this month — all tracked in MANTIQ.\n\nFrom first quote to delivery — every step recorded.\n\n#MANTIQ #Sales #Orders #Egypt",
    "img": "/images/15_sls_phone_l.png"
  },
  {
    "id": "16_sls_big_phone",
    "sys": "sls",
    "type": "phone",
    "week": 4,
    "day": "الاثنين",
    "time": "12:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "🏆 أهداف المبيعات — مرئية ومتتبعة\n\nتابع حصة كل مندوب وعمولاته تلقائياً.\n\n📊 كريم نور: ١٠٢٪ — تجاوز الهدف!\n⚠️ منى عادل: ٥٨٪ — محتاجة دعم\n\nمنطق بيعطيك الصورة الكاملة.\n\n#منطق #مبيعات #أهداف #مصر",
    "en": "🏆 Sales targets — visible and tracked\n\nTrack every rep's quota and commissions automatically.\n\n📊 Kareem Nour: 102% — target exceeded!\n⚠️ Mona Adel: 58% — needs support\n\nMANTIQ gives you the full picture.\n\n#MANTIQ #Sales #Targets #Egypt",
    "img": "/images/16_sls_big_phone.png"
  },
  {
    "id": "17_sls_laptop_orders",
    "sys": "sls",
    "type": "laptop",
    "week": 4,
    "day": "الأربعاء",
    "time": "18:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "📈 متوسط الصفقة ٥٢ ألف جنيه\n\nتحليل كامل لقيمة العملاء ومصادر الإيراد — في منطق للمبيعات.\n\nاعرف مين عميلك الأكثر قيمة وامتى تركز عليه.\n\n#منطق #مبيعات #تحليل #مصر",
    "en": "📈 Average deal value: 52K EGP\n\nFull analysis of customer lifetime value and revenue sources — in MANTIQ Sales.\n\nKnow your most valuable clients and when to focus on them.\n\n#MANTIQ #Sales #Analytics #Egypt",
    "img": "/images/17_sls_laptop_orders.png"
  },
  {
    "id": "18_sls_qa2",
    "sys": "sls",
    "type": "qa",
    "week": 4,
    "day": "الجمعة",
    "time": "15:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "❓ بتخسر صفقات بسبب عروض أسعار بطيئة؟\n\nالعميل مش هيستنى — وانت عارف ده.\n\nمع منطق للمبيعات:\n✅ اعمل عروض أسعار احترافية في دقائق\n✅ أرسل وتتبع حالة كل عرض أونلاين\n✅ احتسب الخصومات والعمولات تلقائياً\n✅ حوّل العرض لطلب بيع بضغطة واحدة\n\n💬 قولنا — بياخد منك عرض السعر قد إيه؟\n\n#منطق #مبيعات #عروض_أسعار #مصر",
    "en": "❓ Losing deals because of slow quotes?\n\nClients won't wait — and you know it.\n\nWith MANTIQ Sales:\n✅ Create professional quotes in minutes\n✅ Send and track every quote online\n✅ Auto-calculate discounts and commissions\n✅ Convert quote to sales order in one click\n\n💬 Tell us — how long does a quote take you?\n\n#MANTIQ #Sales #Quotes #Egypt",
    "img": "/images/18_sls_qa2.png"
  },
  {
    "id": "19_sls_feat1",
    "sys": "sls",
    "type": "features",
    "week": 4,
    "day": "الأحد",
    "time": "11:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "🟠 Sales Tracker — كل دورة المبيعات في مكان واحد\n\n• إدارة الفرص\n• عروض الأسعار الاحترافية\n• طلبات البيع\n• عمولات المندوبين\n• أهداف المبيعات\n• تقارير الإيراد\n\nمنطق — النظام الأول للمبيعات في مصر.\n\n#منطق #مبيعات #Sales #مصر",
    "en": "🟠 Sales Tracker — full sales cycle in one place\n\n• Opportunity management\n• Professional quotations\n• Sales orders\n• Rep commissions\n• Sales targets\n• Revenue reports\n\nMANTIQ — Egypt's #1 sales system.\n\n#MANTIQ #Sales #Egypt",
    "img": "/images/19_sls_feat1.png"
  },
  {
    "id": "20_sls_feat2",
    "sys": "sls",
    "type": "features",
    "week": 4,
    "day": "الثلاثاء",
    "time": "19:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "📊 أرقام مارس ٢٠٢٥\n\n✅ ١٣٨ طلب مُغلق\n✅ ٧٨٪ تحقيق الحصة\n✅ نمو +١٦٪\n✅ متوسط صفقة ٥٢ ألف جنيه\n\nدي نتائج شركة بتستخدم منطق للمبيعات.\n\nعايز نفس النتائج؟ تواصل معنا 👇\n\n#منطق #مبيعات #نتائج #مصر",
    "en": "📊 March 2025 numbers\n\n✅ 138 orders closed\n✅ 78% quota attainment\n✅ +16% growth\n✅ 52K EGP average deal\n\nThese are the results of a company using MANTIQ Sales.\n\nWant the same results? Contact us 👇\n\n#MANTIQ #Sales #Results #Egypt",
    "img": "/images/20_sls_feat2.png"
  },
  {
    "id": "21_hr_phone_r",
    "sys": "hr",
    "type": "phone",
    "week": 5,
    "day": "السبت",
    "time": "09:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "🟣 فريقك يستاهل أكثر\n\nموظفين • رواتب • حضور • أداء • توظيف\n\nكل ده في نظام HR واحد من منطق.\n\n✅ مسير رواتب آمن ودقيق\n✅ حضور وغياب يومي\n✅ تقييم أداء احترافي\n\n#منطق #HR #موارد_بشرية #مصر",
    "en": "🟣 Your team deserves better\n\nEmployees • Payroll • Attendance • Performance • Recruitment\n\nAll in one MANTIQ HR system.\n\n✅ Safe and accurate payroll\n✅ Daily attendance tracking\n✅ Professional performance reviews\n\n#MANTIQ #HR #HumanResources #Egypt",
    "img": "/images/21_hr_phone_r.png"
  },
  {
    "id": "22_hr_laptop_purple",
    "sys": "hr",
    "type": "laptop",
    "week": 5,
    "day": "الاثنين",
    "time": "12:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "👥 ٢٤٨ موظف — مُدارون باحترافية\n\n١.٨ مليون جنيه رواتب — معالجة تلقائية كل شهر.\n\nمع منطق HR — وفّر وقتك وركز على تطوير فريقك.\n\n#منطق #HR #رواتب #مصر",
    "en": "👥 248 employees — managed professionally\n\n1.8M EGP payroll — auto-processed every month.\n\nWith MANTIQ HR — save time and focus on developing your team.\n\n#MANTIQ #HR #Payroll #Egypt",
    "img": "/images/22_hr_laptop_purple.png"
  },
  {
    "id": "23_hr_qa1",
    "sys": "hr",
    "type": "qa",
    "week": 5,
    "day": "الأربعاء",
    "time": "18:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "❓ بتعمل الرواتب كل شهر إزاي؟\n\nلو الإجابة 'Excel' — في طريقة أحسن.\n\nمع منطق HR:\n✅ احتساب تلقائي للراتب والتأمينات والخصومات\n✅ مسير رواتب شهري في دقائق بدل ساعات\n✅ سجل الإجازات والحضور متصل بالراتب\n✅ تقارير ضريبية جاهزة للتقديم فوراً\n\n💬 قولنا — بياخد منك مسير الرواتب قد إيه؟\n\n#منطق #HR #رواتب #مصر",
    "en": "❓ How do you run payroll every month?\n\nIf the answer is 'Excel' — there's a better way.\n\nWith MANTIQ HR:\n✅ Auto-calculate salary, insurance, and deductions\n✅ Monthly payroll in minutes, not hours\n✅ Leave and attendance linked to salary\n✅ Tax reports ready for submission instantly\n\n💬 Tell us — how long does payroll take you?\n\n#MANTIQ #HR #Payroll #Egypt",
    "img": "/images/23_hr_qa1.png"
  },
  {
    "id": "24_hr_tablet_light",
    "sys": "hr",
    "type": "tablet",
    "week": 5,
    "day": "الجمعة",
    "time": "15:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "📋 إدارة بدون جداول\n\nإجازات وحضور وتقييم الأداء في نظام واحد — بدون Excel.\n\nمنطق HR بيحول فوضى الموارد البشرية لنظام واضح.\n\n#منطق #HR #إدارة #مصر",
    "en": "📋 Management without spreadsheets\n\nLeaves, attendance, and performance reviews in one system — no Excel.\n\nMANTIQ HR turns HR chaos into a clear system.\n\n#MANTIQ #HR #Management #Egypt",
    "img": "/images/24_hr_tablet_light.png"
  },
  {
    "id": "25_hr_phone_l",
    "sys": "hr",
    "type": "phone",
    "week": 6,
    "day": "السبت",
    "time": "09:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "🏖️ الإجازات والحضور — بضغطة موافقة\n\n١٢ إجازة معلقة — كلها بضغطة موافقة.\n\nمع منطق HR — الموافقة على الإجازات مش بتاخد أكتر من ثانية.\n\n#منطق #HR #إجازات #مصر",
    "en": "🏖️ Leaves and attendance — one approval click\n\n12 pending leaves — all waiting for one approval click.\n\nWith MANTIQ HR — approving leaves takes less than a second.\n\n#MANTIQ #HR #Leaves #Egypt",
    "img": "/images/25_hr_phone_l.png"
  },
  {
    "id": "26_hr_big_phone",
    "sys": "hr",
    "type": "phone",
    "week": 6,
    "day": "الاثنين",
    "time": "12:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "💰 مسير الرواتب\n\n١.٨ مليون جنيه معالجة تلقائية كل شهر.\n\n✅ أحمد حسن: ٢٦٬٧٠٠ — مدفوع\n✅ سارة مصطفى: ٢٣٬٧٠٠ — مدفوع\n⏳ منى عادل: ١٦٬٢٠٠ — قيد المعالجة\n\nمنطق بيضمن ما حدش يتأخر.\n\n#منطق #HR #رواتب #مصر",
    "en": "💰 Payroll processed\n\n1.8M EGP auto-processed every month.\n\n✅ Ahmed Hassan: 26,700 — Paid\n✅ Sara Mostafa: 23,700 — Paid\n⏳ Mona Adel: 16,200 — Processing\n\nMANTIQ ensures no one is ever late.\n\n#MANTIQ #HR #Payroll #Egypt",
    "img": "/images/26_hr_big_phone.png"
  },
  {
    "id": "27_hr_laptop_dark",
    "sys": "hr",
    "type": "laptop",
    "week": 6,
    "day": "الأربعاء",
    "time": "18:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "🎯 التوظيف أسهل الآن\n\nتابع كل طلب من التقديم حتى التعيين.\n\nمنطق HR بيحول عملية التوظيف من فوضى لنظام واضح ومنظم.\n\n#منطق #HR #توظيف #مصر",
    "en": "🎯 Recruitment just got easier\n\nTrack every application from submission to hire.\n\nMANTIQ HR turns the recruitment process from chaos to a clear, organized system.\n\n#MANTIQ #HR #Recruitment #Egypt",
    "img": "/images/27_hr_laptop_dark.png"
  },
  {
    "id": "28_hr_qa2",
    "sys": "hr",
    "type": "qa",
    "week": 6,
    "day": "الجمعة",
    "time": "15:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "❓ بتعرف أداء موظفيك؟\n\nلو مش بتعمل تقييمات منتظمة — بتخسر فرص تطوير فريقك.\n\nمع منطق HR:\n✅ تقييمات أداء فصلية بمعايير واضحة\n✅ متوسط أداء الفريق ٤.١/٥ — مُتتبَّع تلقائياً\n✅ مقارنة الأداء بين الأقسام والأفراد\n✅ ربط الأداء بالترقيات والمكافآت\n\n💬 قولنا — بتعمل تقييم أداء قد إيه؟\n\n#منطق #HR #أداء_الموظفين #مصر",
    "en": "❓ Do you know how your employees are performing?\n\nIf you're not doing regular reviews — you're missing team development opportunities.\n\nWith MANTIQ HR:\n✅ Quarterly performance reviews with clear criteria\n✅ Team average 4.1/5 — auto-tracked\n✅ Compare performance across departments and individuals\n✅ Link performance to promotions and bonuses\n\n💬 Tell us — how often do you do performance reviews?\n\n#MANTIQ #HR #EmployeePerformance #Egypt",
    "img": "/images/28_hr_qa2.png"
  },
  {
    "id": "29_hr_feat1",
    "sys": "hr",
    "type": "features",
    "week": 6,
    "day": "الأحد",
    "time": "11:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "🟣 HR System — إدارة الموارد البشرية بالكامل\n\n• دليل الموظفين\n• الرواتب والتأمينات\n• الحضور والإجازات\n• تقييم الأداء\n• لوحة متابعة التوظيف\n• التدريب والتطوير\n\nمنطق — النظام الأول للموارد البشرية في مصر.\n\n#منطق #HR #موارد_بشرية #مصر",
    "en": "🟣 HR System — complete human resources management\n\n• Employee directory\n• Payroll and insurance\n• Attendance and leaves\n• Performance reviews\n• Recruitment tracking board\n• Training and development\n\nMANTIQ — Egypt's #1 HR system.\n\n#MANTIQ #HR #HumanResources #Egypt",
    "img": "/images/29_hr_feat1.png"
  },
  {
    "id": "30_hr_feat2",
    "sys": "hr",
    "type": "features",
    "week": 6,
    "day": "الثلاثاء",
    "time": "19:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "📊 ٢٤٨ موظف — مُدارون باحترافية\n\n✅ ١.٨M جنيه رواتب شهرياً\n✅ ٩٤٪ معدل حضور\n✅ ٤.١/٥ متوسط الأداء\n✅ ٨ أقسام مُتكاملة\n\nكل ده بنظام HR واحد من منطق.\n\n#منطق #HR #نتائج #مصر",
    "en": "📊 248 employees — managed professionally\n\n✅ 1.8M EGP monthly payroll\n✅ 94% attendance rate\n✅ 4.1/5 avg performance\n✅ 8 integrated departments\n\nAll with one MANTIQ HR system.\n\n#MANTIQ #HR #Results #Egypt",
    "img": "/images/30_hr_feat2.png"
  },
  {
    "id": "31_fin_phone_r",
    "sys": "fin",
    "type": "phone",
    "week": 7,
    "day": "السبت",
    "time": "09:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "🟢 وضوح مالي كامل\n\nإيرادات ومصروفات وفواتير في مكان واحد.\n\nمع منطق للمالية — مش هتحتاج تسأل المحاسب عن كل حاجة.\n\n✅ P&L لحظي\n✅ فواتير مع VAT ١٤٪\n✅ تدفق نقدي مرئي\n\n#منطق #مالية #محاسبة #مصر",
    "en": "🟢 Complete financial clarity\n\nRevenue, expenses, and invoices in one place.\n\nWith MANTIQ Finance — you won't need to ask your accountant about everything.\n\n✅ Real-time P&L\n✅ Invoices with 14% VAT\n✅ Visual cash flow\n\n#MANTIQ #Finance #Accounting #Egypt",
    "img": "/images/31_fin_phone_r.png"
  },
  {
    "id": "32_fin_laptop_green",
    "sys": "fin",
    "type": "laptop",
    "week": 7,
    "day": "الاثنين",
    "time": "12:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "📈 +٣٨٪ أرباح\n\nنمو صافي الربح مع منطق للمالية.\n\n٣.٦ مليون إيراد — ١.٧ مليون صافي ربح — ٤٧٪ هامش.\n\nدي أرقام حقيقية من شركة بتستخدم منطق.\n\n#منطق #مالية #أرباح #مصر",
    "en": "📈 +38% profit growth\n\nNet profit growth with MANTIQ Finance.\n\n3.6M revenue — 1.7M net profit — 47% margin.\n\nReal numbers from a company using MANTIQ.\n\n#MANTIQ #Finance #Profit #Egypt",
    "img": "/images/32_fin_laptop_green.png"
  },
  {
    "id": "33_fin_qa1",
    "sys": "fin",
    "type": "qa",
    "week": 7,
    "day": "الأربعاء",
    "time": "18:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "❓ بتعرف مصاريف شركتك فين بالظبط؟\n\nلو الإجابة 'تقريباً' — في مشكلة.\n\nمع منطق للمالية:\n✅ تتبع كل مصروف بالفئة والتاريخ والموافق\n✅ مقارنة المصاريف بالميزانية المحددة\n✅ تنبيهات لما أي بند يتجاوز الحد المسموح\n✅ تقرير P&L جاهز في أي وقت\n\n💬 قولنا — بتتابع مصاريفك إزاي؟\n\n#منطق #مالية #محاسبة #مصر",
    "en": "❓ Do you know exactly where your company's money goes?\n\nIf the answer is 'roughly' — there's a problem.\n\nWith MANTIQ Finance:\n✅ Track every expense by category, date, and approver\n✅ Compare expenses against your set budget\n✅ Alerts when any line item exceeds limits\n✅ P&L report ready anytime\n\n💬 Tell us — how do you track your expenses?\n\n#MANTIQ #Finance #Accounting #Egypt",
    "img": "/images/33_fin_qa1.png"
  },
  {
    "id": "34_fin_tablet_light",
    "sys": "fin",
    "type": "tablet",
    "week": 7,
    "day": "الجمعة",
    "time": "15:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "🧾 ضريبة القيمة المضافة ١٤٪\n\nاحتساب تلقائي — جاهز للتدقيق الضريبي في أي وقت.\n\nمنطق بيضمن إن كل فاتورة متوافقة مع اشتراطات مصلحة الضرائب.\n\n#منطق #مالية #ضرائب #مصر",
    "en": "🧾 VAT 14% — auto-calculated\n\nReady for tax audit at any time.\n\nMANTIQ ensures every invoice complies with tax authority requirements.\n\n#MANTIQ #Finance #Tax #Egypt",
    "img": "/images/34_fin_tablet_light.png"
  },
  {
    "id": "35_fin_phone_l",
    "sys": "fin",
    "type": "phone",
    "week": 8,
    "day": "السبت",
    "time": "09:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "📄 الفواتير المتأخرة — متتبعة تلقائياً\n\n٤٢٠ ألف جنيه مستحقات — كل واحدة متتبعة في منطق.\n\nمع منطق للمالية — مش هتنسى فاتورة تاني.\n\n✅ تذكيرات تلقائية للعملاء\n✅ تقرير الفواتير المتأخرة\n✅ حالة كل فاتورة لحظياً\n\n#منطق #مالية #فواتير #مصر",
    "en": "📄 Overdue invoices — auto-tracked\n\n420K EGP outstanding — every one tracked in MANTIQ.\n\nWith MANTIQ Finance — you'll never forget an invoice again.\n\n✅ Auto reminders to clients\n✅ Overdue invoice report\n✅ Live status of every invoice\n\n#MANTIQ #Finance #Invoices #Egypt",
    "img": "/images/35_fin_phone_l.png"
  },
  {
    "id": "36_fin_big_phone",
    "sys": "fin",
    "type": "phone",
    "week": 8,
    "day": "الاثنين",
    "time": "12:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "📊 أرباح وخسائر — واضح ومباشر\n\nتقرير P&L حي — كل رقم مرتبط بالفاتورة الأصلية.\n\n✅ إيراد: +٣.٦M\n❌ مصروفات: -١.٩M\n💚 صافي ربح: ١.٧M جنيه\n\n#منطق #مالية #PnL #مصر",
    "en": "📊 Profit & Loss — clear and direct\n\nLive P&L report — every number linked to the original invoice.\n\n✅ Revenue: +3.6M\n❌ Expenses: -1.9M\n💚 Net profit: 1.7M EGP\n\n#MANTIQ #Finance #PnL #Egypt",
    "img": "/images/36_fin_big_phone.png"
  },
  {
    "id": "37_fin_laptop_dark",
    "sys": "fin",
    "type": "laptop",
    "week": 8,
    "day": "الأربعاء",
    "time": "18:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "✅ جاهز للتدقيق — دايماً\n\nتقارير ضريبية ومحاسبية في أي وقت — بدون ضغط.\n\nمنطق بيحتفظ بكل السجلات تلقائياً ويصدرها بضغطة واحدة.\n\n#منطق #مالية #تدقيق #مصر",
    "en": "✅ Always audit-ready\n\nTax and accounting reports anytime — without stress.\n\nMANTIQ keeps all records automatically and exports them in one click.\n\n#MANTIQ #Finance #Audit #Egypt",
    "img": "/images/37_fin_laptop_dark.png"
  },
  {
    "id": "38_fin_qa2",
    "sys": "fin",
    "type": "qa",
    "week": 8,
    "day": "الجمعة",
    "time": "15:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "❓ بتعمل إيه لما المحاسب يطلب تقرير؟\n\nلو بتدور في أوراق كتير — في طريقة أحسن.\n\nمع منطق للمالية:\n✅ تقارير P&L جاهزة بضغطة واحدة\n✅ فواتير مع VAT 14% محسوبة تلقائياً\n✅ تدفق نقدي مرئي — داخل وخارج\n✅ تصدير Excel للمحاسب فوراً\n\n💬 قولنا — بياخد منك إعداد التقرير قد إيه؟\n\n#منطق #مالية #محاسبة #مصر",
    "en": "❓ What do you do when the accountant asks for a report?\n\nIf you're digging through lots of papers — there's a better way.\n\nWith MANTIQ Finance:\n✅ P&L reports ready in one click\n✅ Invoices with 14% VAT auto-calculated\n✅ Visual cash flow — in and out\n✅ Export Excel to accountant instantly\n\n💬 Tell us — how long does report preparation take you?\n\n#MANTIQ #Finance #Accounting #Egypt",
    "img": "/images/38_fin_qa2.png"
  },
  {
    "id": "39_fin_feat1",
    "sys": "fin",
    "type": "features",
    "week": 8,
    "day": "الأحد",
    "time": "11:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "🟢 Finance Tracker — الوضوح المالي الكامل\n\n• إيرادات ومصروفات\n• فواتير مع VAT ١٤٪\n• أرباح وخسائر\n• إدارة الميزانية\n• تدفق نقدي\n• تقارير ضريبية\n\nمنطق — النظام المالي الأول في مصر.\n\n#منطق #مالية #محاسبة #مصر",
    "en": "🟢 Finance Tracker — complete financial clarity\n\n• Revenue and expenses\n• Invoices with 14% VAT\n• Profit and loss\n• Budget management\n• Cash flow\n• Tax reports\n\nMANTIQ — Egypt's #1 finance system.\n\n#MANTIQ #Finance #Accounting #Egypt",
    "img": "/images/39_fin_feat1.png"
  },
  {
    "id": "40_fin_feat2",
    "sys": "fin",
    "type": "features",
    "week": 8,
    "day": "الثلاثاء",
    "time": "19:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "📊 مارس ٢٠٢٥ — أرقام حقيقية\n\n✅ ٣.٦M جنيه إيراد إجمالي\n✅ ٤٧٪ هامش ربح\n✅ ٨٧٪ تحصيل الفواتير\n✅ ١٠٠٪ متوافق ضريبياً\n\nكل ده بمنطق للمالية.\n\n#منطق #مالية #نتائج #مصر",
    "en": "📊 March 2025 — real numbers\n\n✅ 3.6M EGP total revenue\n✅ 47% profit margin\n✅ 87% invoice collection rate\n✅ 100% tax compliant\n\nAll with MANTIQ Finance.\n\n#MANTIQ #Finance #Results #Egypt",
    "img": "/images/40_fin_feat2.png"
  },
  {
    "id": "41_ac_phone_r",
    "sys": "ac",
    "type": "phone",
    "week": 9,
    "day": "السبت",
    "time": "09:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "🔴 أدر أكاديميتك ببساطة\n\nطلاب • معلمين • جداول • حضور • إيرادات\n\nكل ده في نظام أكاديمي واحد من منطق.\n\n✅ ٣١٢ طالب مُدار\n✅ ٩١٪ معدل حضور\n✅ ١٨٦ ألف جنيه إيراد شهري\n\n#منطق #أكاديمية #تعليم #مصر",
    "en": "🔴 Manage your academy simply\n\nStudents • Teachers • Schedules • Attendance • Revenue\n\nAll in one MANTIQ Academy system.\n\n✅ 312 students managed\n✅ 91% attendance rate\n✅ 186K EGP monthly revenue\n\n#MANTIQ #Academy #Education #Egypt",
    "img": "/images/41_ac_phone_r.png"
  },
  {
    "id": "42_ac_laptop_red",
    "sys": "ac",
    "type": "laptop",
    "week": 9,
    "day": "الاثنين",
    "time": "12:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "🎓 ٣١٢ طالب — بسجل كامل\n\n٩١٪ معدل حضور — ١٨٦ ألف جنيه إيراد شهري.\n\nمنطق بيدير أكاديميتك بدالك — أنت بس تركز على التعليم.\n\n#منطق #أكاديمية #طلاب #مصر",
    "en": "🎓 312 students — with complete records\n\n91% attendance rate — 186K EGP monthly revenue.\n\nMANTIQ manages your academy for you — you just focus on education.\n\n#MANTIQ #Academy #Students #Egypt",
    "img": "/images/42_ac_laptop_red.png"
  },
  {
    "id": "43_ac_qa1",
    "sys": "ac",
    "type": "qa",
    "week": 9,
    "day": "الأربعاء",
    "time": "18:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "❓ بتعرف مين غايب النهارده؟\n\nلو بتعد يدوياً — في طريقة أحسن.\n\nمع منطق للأكاديمية:\n✅ تسجيل حضور الطلاب يومياً بكل فصل\n✅ تقارير حضور أسبوعية وشهرية فورية\n✅ تنبيه تلقائي للولي أمر عند الغياب\n✅ مقارنة الحضور بالتحصيل الدراسي\n\n💬 قولنا — بتتابع الحضور إزاي دلوقتي؟\n\n#منطق #أكاديمية #حضور #مصر",
    "en": "❓ Do you know who's absent today?\n\nIf you're counting manually — there's a better way.\n\nWith MANTIQ Academy:\n✅ Daily attendance per class\n✅ Weekly and monthly reports instantly\n✅ Auto notification to parents on absence\n✅ Compare attendance with academic performance\n\n💬 Tell us — how do you track attendance now?\n\n#MANTIQ #Academy #Attendance #Egypt",
    "img": "/images/43_ac_qa1.png"
  },
  {
    "id": "44_ac_tablet_light",
    "sys": "ac",
    "type": "tablet",
    "week": 9,
    "day": "الجمعة",
    "time": "15:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "👨‍🏫 ٢٤ معلم — منظمون بوضوح\n\nجداول وحصص ومهام كل معلم بوضوح تام.\n\nمنطق بيخلي إدارة المعلمين سهلة وبسيطة.\n\n#منطق #أكاديمية #معلمين #مصر",
    "en": "👨‍🏫 24 teachers — clearly organized\n\nSchedules, lessons, and assignments for every teacher with full clarity.\n\nMANTIQ makes teacher management easy and simple.\n\n#MANTIQ #Academy #Teachers #Egypt",
    "img": "/images/44_ac_tablet_light.png"
  },
  {
    "id": "45_ac_phone_l",
    "sys": "ac",
    "type": "phone",
    "week": 10,
    "day": "السبت",
    "time": "09:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "📚 الطلاب والحضور — سجل كامل\n\n٣١٢ طالب — كل واحد عنده سجل كامل بالحضور والدرجات والسداد.\n\nمع منطق — أي سؤال عن أي طالب ليه إجابة فورية.\n\n#منطق #أكاديمية #طلاب #مصر",
    "en": "📚 Students and attendance — complete records\n\n312 students — each with a full record of attendance, grades, and payment.\n\nWith MANTIQ — any question about any student has an instant answer.\n\n#MANTIQ #Academy #Students #Egypt",
    "img": "/images/45_ac_phone_l.png"
  },
  {
    "id": "46_ac_big_phone",
    "sys": "ac",
    "type": "phone",
    "week": 10,
    "day": "الاثنين",
    "time": "12:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "💵 الإيرادات والمصروفات — كل جنيه متتبع\n\n١٨٦ ألف جنيه شهرياً — كل جنيه داخل وخارج متسجل.\n\n✅ رسوم الطلاب: +١٨٦,٠٠٠\n❌ رواتب المعلمين: -٣٨,٠٠٠\n❌ إيجار: -١٢,٠٠٠\n💚 صافي: ١٢٤,٠٠٠ جنيه\n\n#منطق #أكاديمية #مالية #مصر",
    "en": "💵 Revenue and expenses — every pound tracked\n\n186K EGP monthly — every pound in and out recorded.\n\n✅ Student fees: +186,000\n❌ Teacher salaries: -38,000\n❌ Rent: -12,000\n💚 Net: 124,000 EGP\n\n#MANTIQ #Academy #Finance #Egypt",
    "img": "/images/46_ac_big_phone.png"
  },
  {
    "id": "47_ac_laptop_dark",
    "sys": "ac",
    "type": "laptop",
    "week": 10,
    "day": "الأربعاء",
    "time": "18:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "📊 إيراداتك تحت السيطرة\n\nتتبع المصروفات والإيرادات والعمولات — كل شهر.\n\nمنطق بيديك صورة مالية واضحة لأكاديميتك في أي وقت.\n\n#منطق #أكاديمية #مالية #مصر",
    "en": "📊 Revenue under control\n\nTrack expenses, revenue, and commissions — every month.\n\nMANTIQ gives you a clear financial picture of your academy at any time.\n\n#MANTIQ #Academy #Finance #Egypt",
    "img": "/images/47_ac_laptop_dark.png"
  },
  {
    "id": "48_ac_qa2",
    "sys": "ac",
    "type": "qa",
    "week": 10,
    "day": "الجمعة",
    "time": "15:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "❓ بتعمل إيه لما ولي أمر يسأل عن ابنه؟\n\nلو بتدور في أوراق — في طريقة أحسن.\n\nمع منطق للأكاديمية:\n✅ سجل كامل لكل طالب — حضور ودرجات وسداد\n✅ تواصل مباشر مع أولياء الأمور من النظام\n✅ تقارير أداء فصلية جاهزة للإرسال\n✅ تاريخ كامل منذ يوم التسجيل\n\n💬 قولنا — بتتواصل مع أولياء الأمور إزاي؟\n\n#منطق #أكاديمية #أولياء_أمور #مصر",
    "en": "❓ What do you do when a parent asks about their child?\n\nIf you're searching through papers — there's a better way.\n\nWith MANTIQ Academy:\n✅ Complete record per student — attendance, grades, payment\n✅ Direct communication with parents from the system\n✅ Term performance reports ready to send\n✅ Full history since enrollment day\n\n💬 Tell us — how do you communicate with parents?\n\n#MANTIQ #Academy #Parents #Egypt",
    "img": "/images/48_ac_qa2.png"
  },
  {
    "id": "49_ac_feat1",
    "sys": "ac",
    "type": "features",
    "week": 10,
    "day": "الأحد",
    "time": "11:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "🔴 Academy System — إدارة شاملة للمراكز التعليمية\n\n• سجل الطلاب الكامل\n• إدارة المعلمين\n• الجداول الدراسية\n• الحضور والغياب\n• الإيرادات والمصروفات\n• تقارير الأداء\n\nمنطق — النظام التعليمي الأول في مصر.\n\n#منطق #أكاديمية #تعليم #مصر",
    "en": "🔴 Academy System — complete educational center management\n\n• Full student records\n• Teacher management\n• Class schedules\n• Attendance and absences\n• Revenue and expenses\n• Performance reports\n\nMANTIQ — Egypt's #1 educational system.\n\n#MANTIQ #Academy #Education #Egypt",
    "img": "/images/49_ac_feat1.png"
  },
  {
    "id": "50_ac_feat2",
    "sys": "ac",
    "type": "features",
    "week": 10,
    "day": "الثلاثاء",
    "time": "19:00",
    "platform": "Instagram",
    "notes": "",
    "ar": "📊 ٣١٢ طالب — مُدارون باحترافية\n\n✅ ٩١٪ معدل حضور\n✅ ٢٤ معلم نشط\n✅ ١٨٦ ألف جنيه شهرياً\n✅ ٤ صفوف دراسية\n\nكل ده بنظام أكاديمي واحد من منطق.\n\nعايز تجربة مجانية؟ تواصل معنا 👇\n\n#منطق #أكاديمية #نتائج #مصر",
    "en": "📊 312 students — managed professionally\n\n✅ 91% attendance rate\n✅ 24 active teachers\n✅ 186K EGP monthly revenue\n✅ 4 class years\n\nAll with one MANTIQ Academy system.\n\nWant a free trial? Contact us 👇\n\n#MANTIQ #Academy #Results #Egypt",
    "img": "/images/50_ac_feat2.png"
  }
];
